#!/usr/bin/env python3

import yaml
import argparse
import subprocess
from loadleveller import clusterutils
import glob
import sys
import os

parser = argparse.ArgumentParser(description='This helper program runs a loadleveller Monte Carlo program using a provided YAML-formatted jobfile. The jobfile contains information on how to run the job (what mc binary, mpi-parameters, ...) and a number of tasks with different simulation parameters each. When running on a cluster batch system, the batch script is generated using ygeneratebatchscript.')

parser.add_argument('jobfile', metavar='JOBFILE', help='Configuration file containing all the job information. May be generated using ytaskmaker')
parser.add_argument('-s','--single', action='store_true', help='Run in the single core scheduler mode')
parser.add_argument('-m','--merge', action='store_true', help='Merge the measurement data of all tasks')
parser.add_argument('--force', action='store_true', help='Ignore warnings about possible job corruption')

args = parser.parse_args()

if args.single and args.merge:
    print('Error: cannot merge and run in single mode at the same time.')
    sys.exit(1)

with open(args.jobfile, 'r') as f:
    jobfile = yaml.load(f)

jobconfig_path = os.path.expandvars(os.path.expanduser(jobfile['jobconfig']))
with open(jobconfig_path) as f:
    jobconfig = yaml.load(f)

mcbinary = os.path.expandvars(os.path.expanduser(jobconfig['mc_binary']))

# check age of the different files
binary_modtime = os.stat(mcbinary).st_mtime
jobfile_modtime = os.stat(args.jobfile).st_mtime

try:
    f = next(glob.iglob('{}.data/*/*.h5'.format(args.jobfile))) # only check one of the output files for speed
    data_modtime = os.stat(f).st_mtime

    error = False
    label = 'Warning' if args.force else 'Error'
    if binary_modtime > data_modtime:
        print('{}: binary \'{}\' is newer than the checkpoint files.'.format(label, mcbinary))
        error = True
    if jobfile_modtime > data_modtime:
        print('{}: jobfile \'{}\' is newer than the checkpoint files.'.format(label, args.jobfile))
        error = True
    if not args.force and error:
        print('Use ydelete to start from a blank run or use \'--force\' to proceed if you are sure\nthe changes you made are compatible.')
        sys.exit(1)
except StopIteration:
    pass

if args.single:
    cmd = [mcbinary, 'single', args.jobfile]
    print('$ '+' '.join(cmd))
    subprocess.run(cmd)
elif args.merge:
    subprocess.run([mcbinary, 'merge', args.jobfile])
else:
    clusterutils.run(args.jobfile, jobconfig, [mcbinary, args.jobfile]) 
